### ISSUE TITLE
Upload files without Wifi

### ISSUE THREAD

**Issue by hxhieu** [PocketSprite/8bkc-sdk#11]
Hi,

I am sorry this has been mentioned/suggested before but how could we do the above?
i.e. my work station is in the local network but doesn't have Wifi so cannot connect to the PocketSprite AP.
Can this be done via USB instead?

Thanks.

**Comment by thedicemaster** [comment]
not possible, as is documented here:
https://github.com/PocketSprite/8bkc-sdk/blob/master/docs/hardware/specs.rst
the usb port is only connected to the charging circuit, there's no data connection.

it might be possible to add support for transfers through Bluetooth or a Wi-Fi router/hotspot, but that would be a lot of work(and Wi-Fi would be a pain to connect)
I'm not a developer though, so I can't guarantee if either of these is feasible.

**Comment by hxhieu** [comment]
OK , thanks for the details.
Then I guess the solution for me now is to transfer the files to the phone while the phone connected to PocketSprite AP :)
