### ISSUE TITLE
calling sndmixer_init() crashes chooser.app

### ISSUE THREAD

**Issue by rorosaurus** [PocketSprite/8bkc-sdk#13]
Whenever I make a call like `sndmixer_init(2, 22050);` in my custom chooser.app, the app crashes and reverts back to the usual chooser.app.  I confirmed the custom app works fine without this call, but the audio I'm trying to play obviously doesn't play.

Is there an easy way to capture error logs and identify the issue?  Or do you happen to know if there's a reason this shouldn't be possible in the chooser.app?

**Comment by Spritetm** [comment]
It should be possible, for sure. I'm planning on adding support for logging to an appfs file as well as crashdumping somewhere, but that's not in the SDK yet. For now, can you tell me where you inserted the call to sndmixer_init?

**Comment by Spritetm** [comment]
It should be possible, for sure. I'm planning on adding support for logging to an appfs file as well as crashdumping somewhere, but that's not in the SDK yet. For now, can you tell me where you inserted the call to sndmixer_init?

**Comment by rorosaurus** [comment]
I've tried `app_main()` in `main.c` (trying to mimic the usage from fluppy), after the call to `kchal_init_sdk()`.  I've also tried in `guiInit()` and `guiMenu()` in the `gui.c`, but that's probably not the best place for it. :)

I've included `sndmixer.h` and added it to the makefile as well, everything seems to compile with no issues.  When I uncomment the single line to init sndmixer, the app crashes and reverts back to the stock chooser.app.

You can see the changes I made here: https://github.com/rorosaurus/8bkc-bmo-chooser/commit/cec9f6e49c4559540759b64dd5cc855c92926a7e

While I have you here, I want to thank you for this awesome little project, and for inspiring me to spend more time making things. :)

**Comment by Spritetm** [comment]
Should be working if you do a git pull in the SDK dir :)
