### ISSUE TITLE
License

### ISSUE THREAD

**Issue by renzenicolai** [PocketSprite/8bkc-sdk#22]
I want to use this code in a project, but it's not clear to me under which license I'm allowed to do so.

Could you please add a license file to this repository? If possible I'd love to be able to use this code under a nonrestrictive license like MIT, BSD or Apache 2.

**Comment by Spritetm** [comment]
Huh, you are right, I never added license headers. Will do that when I have some time. Assume that the code I wrote is under the Beer-Ware license; the other code (mostly Espressif stuff) is under their own (mostly Apache2) license.

**Comment by renzenicolai** [comment]
Would you be alright with a more widely known license such as MIT?

I've looked around at your other projects and I think this is the license header.

```
/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * Jeroen Domburg <jeroen@spritesmods.com> wrote this file. As long as you retain 
 * this notice you can do whatever you want with this stuff. If we meet some day, 
 * and you think this stuff is worth it, you can buy me a beer in return. 
 * ----------------------------------------------------------------------------
*/
```

**Comment by Spritetm** [comment]
Yep. And no, Beer-ware is fully FSF-approved and for this stuff perfectly matches my thoughts about this. Please, don't bug me about the license anymore, or I'll change it to WTFPL :P

**Comment by renzenicolai** [comment]
Point taken, I will close this issue. Licenses are boring stuff anyway 😄
