### ISSUE TITLE
fake hardware doesn't seem to turn off the appfs location compiling

### ISSUE THREAD

**Issue by konsgn** [PocketSprite/8bkc-sdk#3]
When compiling against fake hardware, The app seems to be compiled and flashed to location 0x9000, causing it to run whatever previous code you had on it rather than the direct-boot to app expected..

Working on fixing that now.

**Comment by konsgn** [comment]
woops, nvm, just had ta do a : 
"make partition_table-flash"

**Comment by Spritetm** [comment]
In general, if you run ``make flash``, it should flash everything (app, partition table, bootloader) which should just make it work.

**Comment by konsgn** [comment]
well now, that's just too easy ;)
