### ISSUE TITLE
upgrading fake pocket sprite hardware

### ISSUE THREAD

**Issue by blockda** [PocketSprite/8bkc-sdk#7]
I'm using the esp32-wrover-kit to get a head start on programming for the pocket sprite. I have a plan to upgrade the flash on the kit to have 16 megabytes like the pocketsprite. Is there any recommendations or procedures that I should do to get the real pocket sprite hardware build running on the wrover kit? or at least more real with appfs and hal support.

In 8bkc-components/8bkc-hal/kchal-fake.c around line 325 there is the initialization for appfs that has been commented out. If I remove the comments and initialize appfs (provided the kit has enough flash) will this enable appfs support?

**Comment by Spritetm** [comment]
You probably also need a partition table that has an appfs partition. Furthermore, I'm not sure if there are other things in the 'fake' HAL that may stop the appfs from working.

**Comment by blockda** [comment]
My plan to upgrade the flash probably isn't going to work or will permanently alter my wrover board. The plan was either replacing the chip after removing the protective metal shield on the wrover module, or put the new flash chip on a breakout, run wires to it, and pick a new slave select pin, burn the wrover configuration efuses to make the esp use the new, larger flash chip. Putting it on a breakout probably wouldn't work well because it would have to run at <10Mhz to work with the breakout and wires.

I want to test functionality of saving files from my utility to appfs so they can be retrieved over the wifi. This also will require turning on the wifi on the wrover board which it doesn't seem to be happening in the fake pocket sprite build. Is it possible to flash a small appfs partition to the fake pocket sprite build to test saving small files? Where should I start looking to do that? And where should I look to turn on the wifi in fake hardware?

**Comment by Spritetm** [comment]
WiFi can be turned on using the standard esp-idf functionality. For appfs compatibility... if all you want to do is to save a file, you can probably get away with creating an appfs partition and calling `appfsInit(0x43, 3);` manually.

**Comment by Spritetm** [comment]
Gonna close this as this has been open for a while.

**Comment by ghost** [comment]
i have trouble  in  8bkc-components/8bkc-hal/kchal-fake.c , but i u the ESP32 DEVKITTV1. @@ how can i fix this
